// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
)

type Querier interface {
	GetIssues(ctx context.Context) ([]*Issue, error)
}

var _ Querier = (*Queries)(nil)
