services:
  postgres:
    image: "postgres:18.0"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: issuefinder
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
